### ISSUE TITLE
FEATURE: Provide a migration guide for version 2

### ISSUE THREAD

**Issue by totegsito** [onebeyond/confabulous#20]
As there has been a major update on this package, adding a Migration guide for version 2 would be very helpful. 

## Detailed Description

Add a section on the README.md with some instructions on how to update to version 2.

## Context

We have some security vulnerabilities related to Confabulous 1.7.0. We tried to update the package to the latest one but as it was a major version we were not able to make it work.

## Your Environment
* Version used: 1.7.0

**Comment by cressie176** [comment]
Hi @totegsito,
Did you see the [change log](https://github.com/onebeyond/confabulous/blob/master/CHANGELOG.md)?

**Comment by cressie176** [comment]
Closing due to lack of response
